# Generated by Django 2.2.9 on 2022-02-24 19:57

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='loja',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Base')),
                ('nome', models.CharField(max_length=122)),
                ('descricao', models.TextField(max_length=250)),
                ('tipo', models.CharField(choices=[('AÇÃO', 'AÇÃO'), ('ESPORTES', 'ESPORTES'), ('RPG', 'RPG')], max_length=1)),
                ('quant', models.CharField(choices=[('EM ESTOQUE', 'EM ESTOQUE'), ('SEM ESTOQUE', 'SEM ESTOQUE')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=2)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=api.models.upload_image_jogos)),
            ],
            bases=('api.base',),
        ),
    ]
