# Generated by Django 2.2.9 on 2022-02-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220224_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='quant',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='tipo',
        ),
    ]
