# Generated by Django 2.2.9 on 2022-02-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220225_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='estoque',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Base')),
                ('vendedor', models.CharField(max_length=50, unique=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loja')),
            ],
            bases=('api.base',),
        ),
    ]
