# Generated by Django 2.2.9 on 2022-02-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'estoque', 'verbose_name_plural': 'estoques'},
        ),
        migrations.AlterModelOptions(
            name='loja',
            options={'verbose_name': 'jogo', 'verbose_name_plural': 'jogos'},
        ),
    ]
